@startuml
class logic.task.TaskManager {
+ {static} ArrayList<Task> getTaskByType(ArrayList<Class>)
+ {static} void deleteDuplicateTasks()
+ {static} boolean instanceOf(Class,Class)
}

abstract class logic.task.Task {
- String name
- double workload
+ {abstract}String fullTaskName()
+ String toString()
+ String getName()
+ void setName(String)
+ double getWorkload()
+ void setWorkload(double)
}


interface interfaces.Computable {
+ double compute(ProcessUnit)
}

class logic.task.RenderTask {
+ double compute(ProcessUnit)
+ double parallelCompute(ProcessUnit)
+ void duplicateTask(int)
+ String fullTaskName()
}

class logic.task.CalculationTask {
+ double compute(ProcessUnit)
+ void changeWorkload(int)
+ void modify(int)
+ String fullTaskName()
}

class application.Main {
+ {static} ArrayList<ProcessUnit> processUnits
+ {static} Scanner scanner
+ {static} void main(String[])
+ {static} void initTask()
+ {static} void initProcessUnit()
+ {static} void addProcessorUnit()
+ {static} void addTask()
+ {static} void showProcessorUnits()
+ {static} void showTasks(ArrayList<Task>)
+ {static} void estimateTask()
+ {static} void modifyTask()
}


class logic.compute.ComputeUnit {
+ boolean canCompute(Task)
}

interface interfaces.Duplicatable {
+ void duplicateTask(int)
}

interface interfaces.Parallelizable {
+ double parallelCompute(ProcessUnit)
}

abstract class logic.compute.ProcessUnit {
- String modelName
- int coreNumber
- double clockSpeed
+ String getModelType()
+ String getModelName()
+ void setModelName(String)
+ double compute(Task)
+ double parallelCompute(Task)
+ {abstract}boolean canCompute(Task)
+ int getCoreNumber()
+ void setCoreNumber(int)
+ double getClockSpeed()
+ void setClockSpeed(double)
}


class logic.task.TaskList {
- {static} ArrayList<Task> tasks
+ {static} ArrayList<Task> getTasks()
+ {static} Task getTask(int)
+ {static} void setTasks(ArrayList<Task>)
+ {static} void addTasks(Task)
+ {static} void removeTask(int)
}


class logic.task.SortTask {
+ double compute(ProcessUnit)
+ double parallelCompute(ProcessUnit)
+ void mergeTask(int)
+ void modify(int)
+ String fullTaskName()
}

interface interfaces.Modifiable {
+ void modify(int)
}

class logic.compute.GraphicUnit {
+ boolean canCompute(Task)
+ double compute(Task)
}

class logic.task.SimpleTask {
+ String fullTaskName()
}



interfaces.Computable <|.. logic.task.RenderTask
interfaces.Parallelizable <|.. logic.task.RenderTask
interfaces.Duplicatable <|.. logic.task.RenderTask
logic.task.Task <|-- logic.task.RenderTask
interfaces.Computable <|.. logic.task.CalculationTask
interfaces.Modifiable <|.. logic.task.CalculationTask
logic.task.Task <|-- logic.task.CalculationTask
logic.compute.ProcessUnit <|-- logic.compute.ComputeUnit
interfaces.Computable <|.. logic.task.SortTask
interfaces.Modifiable <|.. logic.task.SortTask
interfaces.Parallelizable <|.. logic.task.SortTask
logic.task.Task <|-- logic.task.SortTask
logic.compute.ProcessUnit <|-- logic.compute.GraphicUnit
logic.task.Task <|-- logic.task.SimpleTask
@enduml